---
minimum_pre_commit_version: 2.4.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: trailing-whitespace   # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending     # Replaces or checks mixed line ending.
        args: [--fix=lf]
      - id: end-of-file-fixer     # Makes sure files end in a newline and only a newline.
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: check-ast             # Simply check whether files parse as valid python.

  # ----- Formatting ---------------------------------------------------------------------------->
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        name: Rewrite Code to be Py3.8+
        args: [
          --py38-plus
        ]
        files: ^((setup|noxfile)|(src|tests)/.*)\.py$
        exclude: src/passivbot/version.py

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        args: [
          --py3-plus,
          --application-directories=.:src,
        ]
        exclude: src/passivbot/version.py

  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black
        args: [-l 100]
        exclude: src/passivbot/version.py

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.11.0
    hooks:
      - id: blacken-docs
        args: [--skip-errors]
        files: ^(docs/.*\.rst|src/passivbot/.*\.py)$
        additional_dependencies: [black==21.10b0]
  # <---- Formatting -----------------------------------------------------------------------------

  # ----- Security ------------------------------------------------------------------------------>
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.0"
    hooks:
      - id: bandit
        alias: bandit-code
        name: Run bandit against the code base
        args: [--silent, -lll, --skip, B701]
        files: ^(?!tests/).*\.py$
        exclude: src/passivbot/version.py
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.0"
    hooks:
      - id: bandit
        alias: bandit-tests
        name: Run bandit against the test suite
        args: [--silent, -lll, --skip, B701]
        files: ^tests/.*
  # <---- Security -------------------------------------------------------------------------------

  # ----- Code Analysis ------------------------------------------------------------------------->
  - repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
        exclude: ^(src/passivbot/version\.py|\.pre-commit-hooks/.*\.py)$
        additional_dependencies:
        - flake8-mypy-fork
        - flake8-docstrings
        - flake8-typing-imports

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        name: Run mypy against source
        files: ^src/.*\.py$
        args: [--strict]
        additional_dependencies:
          - types-attrs
          - types-setuptools
          - types-python-dateutil
          - types-tabulate
          - pydantic

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        name: Run mypy against tests
        files: ^tests/.*\.py$
        args: []
        additional_dependencies:
          - types-attrs
          - types-setuptools
          - types-python-dateutil
          - pydantic
  # <---- Code Analysis --------------------------------------------------------------------------
