source ./run_server_live_bybit_tedy.sh
sleep 4
source ./run_server_live_bybit_tedyptedtoSUB1.sh
sleep 4
source ./run_server_live_bybit_tedyptedtoSUB2.sh
sleep 4
source ./run_server_live_bybit_tedyptedtoSUB3.sh
sleep 4
source ./run_server_live_sawyer.sh